### PR TITLE
Fix operation extension options when using a vue component

### LINKED ISSUE #25900: Bug Report: Operation Extension Options Broken Since 11.7.0
### Describe the Bug

From Directus 11.7.0 onwards, there is a change that causes Vue components used in operation extension options to break.

### To Reproduce

1. Install the “HubSpot API Operation” extension from the marketplace.
2. Add it to a Flow step in Directus.
3. Attempt to save the flow step.

**Observed Behavior**

- The operation options Vue components fail to render/save correctly.
- In the developer console, the following error appears:
`TypeError: (intermediate value)(...).reduce is not a function`

**Expected Behavior**
- Options components should render correctly.
- Saving the flow step should work without JavaScript errors.

**Additional Context**
- This issue appears only from Directus 11.7.0 onwards.
- Related extensions from the marketplace, like HubSpot API Operation, are affected.

**Environment**
- Directus version: 11.7.0+
- Browser: [e.g., Chrome 140]
- Extension: HubSpot API Operation from Marketplace

**Possible Impact**
- Any operation extension using custom Vue components for options may be broken.

### Directus Version

v.11.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

_No response_

### PR DESCRIPTION
**Pull request by br41nslug**
## Scope

This regression was caused by https://github.com/directus/directus/pull/25047 and https://github.com/directus/directus/pull/24963 introducing the `getDefaultValuesFromFields` function

What's changed:

- Only use the `getDefaultValuesFromFields` function if there is an array (this function was throwing the `().reduce` error for non-array input)

## Potential Risks / Drawbacks

- Not sure but i think this is fairly isolated

## Tested Scenarios

- Install the Hubspot Operation from Directus Labs and use it in a flow

## Review Notes / Questions

- Is this the right solution?
- Are there unforeseen issues with bypassing the defaults like this?

Fixes #25900

### CODE REVIEW

File: app/src/modules/settings/routes/flows/components/operation-detail.vue [hunk 1]
```diff
@@ -121,7 +121,7 @@ function saveOperation() {
 
 	saving.value = true;
 
-	const defaultValues = operationOptions.value
+	const defaultValues = Array.isArray(operationOptions.value)
```
Comment (ComfortablyCoding) [inline app/src/modules/settings/routes/flows/components/operation-detail.vue]: As object (i.e. component) should bypass defaults should we have it return undefined in the `operationOptions` computed on L109? We will no longer need to worry about this caveat for future usage.

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀
