### ISSUE TITLE
TypeError: cookieHeader.replace is not a function

### ISSUE THREAD

**Issue by tim-smart** [directus/directus#17905]
### Describe the Bug

After updating to 9.23.3 directus started crashing with the following error:

```
TypeError: cookieHeader.replace is not a function
    at redactHeaderCookie (/directus/dist/utils/redact-header-cookies.js:7:37)
    at res (/directus/dist/logger.js:118:97)
    at Object.wrappedResSerializer [as res] (/directus/node_modules/.pnpm/pino-std-serializers@6.0.0/node_modules/pino-std-serializers/index.js:31:14)
    at Pino.asJson (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/tools.js:132:33)
    at Pino.write (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/proto.js:205:28)
    at Pino.LOG [as info] (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/tools.js:62:21)
    at onResFinished (/directus/node_modules/.pnpm/pino-http@8.3.3/node_modules/pino-http/logger.js:124:15)
    at ServerResponse.onResponseComplete (/directus/node_modules/.pnpm/pino-http@8.3.3/node_modules/pino-http/logger.js:173:14)
    at ServerResponse.emit (node:events:525:35)
    at onFinish (node:_http_outgoing:989:10)
```

### To Reproduce

Our setup is using microsoft oauth for authentication.

### Hosting Strategy

Self-Hosted (Docker Image)
