### PR TITLE
Fix auto-casting of array like values in env

### LINKED ISSUE #12259: Cross-Origin Request Blocked with CSV value in CORS_ORIGIN setting
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Since `9.7.0` CORS has been disabled by default, I need it though so I thought might as well re-enable it but this time restrict to only specific domains. The documentation says using a CSV of domains is permitted: https://docs.directus.io/configuration/config-options/#cors

Turns out it doesn't work, because it just sets the cors origin header to the CSV value instead of matching domains and then only setting the matched domain as the origin value. The CORS origin header can only contain one domain and it needs to be the same one as the one you are on, otherwise CORS requests are invalid. See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

> `<origin>` Specifies an origin. Only a single origin can be specified. If the server supports clients from multiple origins, it must return the origin for the specific client making the request.

### To Reproduce

Set `CORS_ORIGIN` in `.env` file to a CSV of domains.

### Errors Shown

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.gastrodino.de/api/items/products (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match **‘http://localhost:4200,https://www.gastrodino.com’**

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

MariaDB 10.3.34

### What browser are you using?

Chrome Latest

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Ubuntu Server 20.04, npm installation with a systemd service running it

### PR DESCRIPTION
**Pull request by rijkvanzanten**
As per the docs, CSV like values in the .env should be treated as an array by default:

```
STORAGE_LOCATIONS="s3,local,example"
// ["s3", "local", "example"]
```

However, the JSON parsing:

https://github.com/directus/directus/blob/51ec656a064a1c0784098a5ef738b2e6cdd74ab7/api/src/env.ts#L295

revered the array cast back to the original string value.

Fixes https://github.com/directus/directus/issues/12259

### CODE REVIEW

**Review by licitdev — APPROVED** [review]

**Comment by u12206050** [comment]
Since 9.7.1 this env setting is causing issues.

Currently setting is: gcs,local
but since updating to 9.7.1 I am getting the `*:split is not a function error.`

**Comment by rijkvanzanten** [comment]
> Since 9.7.1 this env setting is causing issues.
> 
> Currently setting is: gcs,local but since updating to 9.7.1 I am getting the `*:split is not a function error.`

Interesting one. That's actually a problem in the storage validation using the location name rather than the driver. Pushing up a fix now 👍🏻
