### ISSUE TITLE
Flows - Run Script breaks with axios module allowed

### ISSUE THREAD

**Issue by domdus** [directus/directus#18049]
### Describe the Bug

After update from 9.23.1 to 9.23.4 - all my flows that include a Run Script operation stopped working.
I use axios here and there so my config includes:
`FLOWS_EXEC_ALLOWED_MODULES`=axios

Now ANY of the flows stop at Run Script giving the following message (no matter if axios actually used):
```
{
  "message": "(0 , node_module_1.isBuiltin) is not a function"
}
```

I noticed some recent change https://github.com/directus/directus/pull/17866 that introduced `FLOWS_EXEC_ALLOWED_BUILTINS`.

I'm not yet sure if this thing here is a bug or is there anything I need to change in my config?

---

RUN SCRIPT (example without axios)
<img width="434" alt="image" src="https://user-images.githubusercontent.com/67951828/229833897-77647c1e-5f02-4325-a845-2a6b876b12f0.png">

LOG
<img width="430" alt="image" src="https://user-images.githubusercontent.com/67951828/229833256-fd8784b9-5dbe-41d2-a0ff-61f90fc828e9.png">

### To Reproduce

- Add axios to `FLOWS_EXEC_ALLOWED_MODULES` config
- Create a flow that contains a Run Script operation
- Trigger the flow and see it breaking at Run Script

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment]
Directus is targeting the latest LTS version of Node.js which currently is v18 (see https://github.com/nodejs/release#release-schedule). Please update to this version.
