### PR TITLE
fix LOGGER_LEVELS array being split as string

### LINKED ISSUE #12339: TypeError: loggerEnvConfig.levels.split is not a function
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After update from Directus v9.7.0 to v9.7.1...

We have this error:

```
/node_modules/directus/dist/logger.js:46
    for (const el of loggerEnvConfig.levels.split(',')) {
                                            ^

TypeError: loggerEnvConfig.levels.split is not a function or its return value is not iterable
```

### To Reproduce

We have this config:

```
LOG_STYLE="raw"
LOGGER_LEVELS="trace:DEBUG,debug:DEBUG,info:INFO,warn:WARNING,error:ERROR,fatal:CRITICAL"
LOGGER_MESSAGE_KEY="message"
```

And just update from Directus v9.7.0 to v9.7.1 and run:

```
npx directus start
```

### Errors Shown

```
/node_modules/directus/dist/logger.js:46
    for (const el of loggerEnvConfig.levels.split(',')) {
                                            ^

TypeError: loggerEnvConfig.levels.split is not a function or its return value is not iterable
```

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Running locally

### PR DESCRIPTION
**Pull request by azrikahar**
Fixes #12339

This is due to #12330 fixes csv to be treated as array correctly, but the codebase here still treats it as a string and attempts to `.split` an array which causes the error.

### CODE REVIEW

File: api/src/logger.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ const loggerEnvConfig = getConfigFromEnv('LOGGER_', 'LOGGER_HTTP');
 if (loggerEnvConfig.levels) {
 	const customLogLevels: { [key: string]: string } = {};
 
-	for (const el of loggerEnvConfig.levels.split(',')) {
+	for (const el of loggerEnvConfig.levels) {
```
Comment (licitdev) [inline api/src/logger.ts:27]: Think we should be wrapping it in `toArray()` as it will be of `string` type if there's only one level.

**Review by rijkvanzanten — APPROVED** [review]
