### ISSUE TITLE
Having more than one value in AUTH_PROVIDERS throws an error

### ISSUE THREAD

**Issue by adanielyan** [directus/directus#12403]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After upgrading to 9.7.1 I cannot start directus. It exists with the error below:

```
/Users/adanielyan/Projects/directus/node_modules/directus/dist/utils/track.js:63
            providers: env_1.default.AUTH_PROVIDERS.split(',')
                                                    ^

TypeError: env_1.default.AUTH_PROVIDERS.split is not a function
    at getEnvInfo (/Users/adanielyan/Projects/directus/node_modules/directus/dist/utils/track.js:63:53)
    at async track (/Users/adanielyan/Projects/directus/node_modules/directus/dist/utils/track.js:17:22)
```
My AUTH_PROVIDERS has 2 comma separated values.

```ini
AUTH_PROVIDERS="local,google"
```

### To Reproduce

1. Add more than one AUTH_PROVIDERS
2. Upgrade directus to v9.7.1
3. Try starting it with `npx directus start`

### Errors Shown

```
/Users/adanielyan/Projects/directus/node_modules/directus/dist/utils/track.js:63
            providers: env_1.default.AUTH_PROVIDERS.split(',')
                                                    ^

TypeError: env_1.default.AUTH_PROVIDERS.split is not a function
    at getEnvInfo (/Users/adanielyan/Projects/directus/node_modules/directus/dist/utils/track.js:63:53)
    at async track (/Users/adanielyan/Projects/directus/node_modules/directus/dist/utils/track.js:17:22)
```

### What version of Directus are you using?

v9.7.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres in docker

### What browser are you using?

N/A

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment]
Already resolved by #12370.

**Comment by adanielyan** [comment]
> Already resolved by #12370.

👍🏼
