### ISSUE TITLE
Spot working OKTA SSO 

### ISSUE THREAD

**Issue by AndreyNovik1993** [directus/directus#17924]
### Describe the Bug

Users can't logging by OKTA openid config. 
The config didn't change but after update to 9.23.3 version, It stopped working, For each log in pod crashed and the error is:
[14:37:20] GET /auth/login/okta?redirect=https://*/admin/login?continue 302 18ms
/directus/dist/utils/redact-header-cookies.js:7
        cookieHeader = cookieHeader.replace(re, `$1--redacted--`);
                                    ^

TypeError: cookieHeader.replace is not a function
    at redactHeaderCookie (/directus/dist/utils/redact-header-cookies.js:7:37)
    at res (/directus/dist/logger.js:118:97)
    at Object.wrappedResSerializer [as res] (/directus/node_modules/.pnpm/pino-std-serializers@6.0.0/node_modules/pino-std-serializers/index.js:31:14)
    at Pino.asJson (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/tools.js:132:33)
    at Pino.write (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/proto.js:205:28)
    at Pino.LOG [as info] (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/tools.js:62:21)
    at onResFinished (/directus/node_modules/.pnpm/pino-http@8.3.3/node_modules/pino-http/logger.js:124:15)
    at ServerResponse.onResponseComplete (/directus/node_modules/.pnpm/pino-http@8.3.3/node_modules/pino-http/logger.js:173:14)
    at ServerResponse.emit (node:events:525:35)
    at onFinish (node:_http_outgoing:989:10)

Node.js v18.15.0

### To Reproduce

click login to OKTA bottom 

### Hosting Strategy

Self-Hosted (Docker Image)
