### ISSUE TITLE
TypeError: loggerEnvConfig.levels.split is not a function

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#12339]
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After update from Directus v9.7.0 to v9.7.1...

We have this error:

```
/node_modules/directus/dist/logger.js:46
    for (const el of loggerEnvConfig.levels.split(',')) {
                                            ^

TypeError: loggerEnvConfig.levels.split is not a function or its return value is not iterable
```

### To Reproduce

We have this config:

```
LOG_STYLE="raw"
LOGGER_LEVELS="trace:DEBUG,debug:DEBUG,info:INFO,warn:WARNING,error:ERROR,fatal:CRITICAL"
LOGGER_MESSAGE_KEY="message"
```

And just update from Directus v9.7.0 to v9.7.1 and run:

```
npx directus start
```

### Errors Shown

```
/node_modules/directus/dist/logger.js:46
    for (const el of loggerEnvConfig.levels.split(',')) {
                                            ^

TypeError: loggerEnvConfig.levels.split is not a function or its return value is not iterable
```

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Running locally

**Comment by abdonrd** [comment]
Here:

https://github.com/directus/directus/blob/2e63b49ec425ecea897964bdc382304a1e2207b0/api/src/logger.ts#L27

Looks like `loggerEnvConfig.levels` is an array:

```
[
  'trace:DEBUG',
  'debug:DEBUG',
  'info:INFO',
  'warn:WARNING',
  'error:ERROR',
  'fatal:CRITICAL'
]
```

**Comment by azrikahar** [comment]
Thanks for confirming the difference between `9.7.1` and `9.7.0`. It should be due to #12330, which actually is correcting it! It should have been an array from the get go, rather than a string.

**Comment by azrikahar** [comment]
Just to offer a workaround while the fix get released in a future version, you should be able to temporarily force it as a string by doing `LOGGER_LEVELS="string:trace:DEBUG,debug:DEBUG,info:INFO,warn:WARNING,error:ERROR,fatal:CRITICAL"`. Tested that on `9.7.1` and it works on my end. Hope that helps! 👍

**Comment by abdonrd** [comment]
Thanks @azrikahar!
