### ISSUE TITLE
cannot login with auth0 using v9.23.3

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#17912]
### Describe the Bug

when trying to login, nothing happens and the browser console shows a failed http request:

`Failed to load resource: the server responded with a status of 401 () /auth/refresh`

```json
{"errors":[{"message":"Route /auth/refresh doesn't exist.","extensions":{"code":"ROUTE_NOT_FOUND"}}]}
```

---

my auth config:

```env
AUTH_AUTH0_CLIENT_ID=<client_id>
AUTH_AUTH0_CLIENT_SECRET=<client_secret>
AUTH_AUTH0_DRIVER=openid
AUTH_AUTH0_ISSUER_URL=<issuer_url>
AUTH_DISABLE_DEFAULT=true
AUTH_PROVIDERS=auth0
```

---

it works with [v9.23.1](https://github.com/directus/directus/releases/tag/v9.23.1)

### To Reproduce

setup auth0 as the auth method (see config above) and try to login using [v9.23.3](https://github.com/directus/directus/releases/tag/v9.23.3)

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by timnis** [comment]
Just upgraded from v9.23.1 to v9.23.3 and cannot login either with using Keycloak.

My config
`     
      AUTH_PROVIDERS: "keycloak"
      AUTH_KEYCLOAK_DRIVER: "openid"
      AUTH_KEYCLOAK_CLIENT_ID: "directus-prod"
      AUTH_KEYCLOAK_CLIENT_SECRET: "xxx"
      AUTH_KEYCLOAK_ISSUER_URL: "https://id.xxx.com/realms/master/.well-known/openid-configuration"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "email"
      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "false"
      AUTH_KEYCLOAK_REQUIRE_VERIFIED_EMAIL: "false"
`

and error
`
directus  | [09:16:31] GET /auth 200 7ms
directus  | [09:16:31] GET /assets/d9241159-cadf-4028-8ccb-107d4fd58367?download=true 403 8ms
directus  | [09:16:32] GET /auth/login/keycloak?redirect=https://directus.xxx.com/admin/login?continue 302 7ms
directus  | /directus/dist/utils/redact-header-cookies.js:7
directus  |         cookieHeader = cookieHeader.replace(re, `$1--redacted--`);
directus  |                                     ^
directus  |
directus  | TypeError: cookieHeader.replace is not a function
directus  |     at redactHeaderCookie (/directus/dist/utils/redact-header-cookies.js:7:37)
directus  |     at res (/directus/dist/logger.js:118:97)
directus  |     at Object.wrappedResSerializer [as res] (/directus/node_modules/.pnpm/pino-std-serializers@6.0.0/node_modules/pino-std-serializers/index.js:31:14)
directus  |     at Pino.asJson (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/tools.js:132:33)
directus  |     at Pino.write (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/proto.js:205:28)
directus  |     at Pino.LOG [as info] (/directus/node_modules/.pnpm/pino@8.11.0/node_modules/pino/lib/tools.js:62:21)
directus  |     at onResFinished (/directus/node_modules/.pnpm/pino-http@8.3.3/node_modules/pino-http/logger.js:124:15)
directus  |     at ServerResponse.onResponseComplete (/directus/node_modules/.pnpm/pino-http@8.3.3/node_modules/pino-http/logger.js:173:14)
directus  |     at ServerResponse.emit (node:events:525:35)
directus  |     at onFinish (node:_http_outgoing:989:10)
directus  |
directus  | Node.js v18.15.0
`

**Comment by azrikahar** [comment]
I believe this is the same issue as #17905, let's consolidate this over there 👍
